name: Build to DOM Cloud

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  SERVER_HOST: spiritstead@sgp.domcloud.co

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Run clean install
      run: npm ci
    - name: Build release binary
      run: npm run build
      # 1. Install the SSH identifier from action secrets 
      # 2. Kill the app (unlocks the binary for writing)
      # 3. Copy app binary to server
      # 4. Also copy static files also needed by the binaries
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY_B64 }}" | base64 -d > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Debug SSH
      run: |
        ls -la ~/.ssh
        ssh -vvv -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ env.SERVER_HOST }} "echo SSH OK"
    - name: Test SSH Connection
      run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ env.SERVER_HOST }} "echo SSH OK"
    - name: Deploy Astro Build
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r dist/. ${{ env.SERVER_HOST }}:public_html/
