name: Build to DOM Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SERVER_HOST: spiritstead@sgp.domcloud.co

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Node
      uses: npm install
    - name: Run clean install
      uses: npm ci
    - name: Build release binary
      run: npm run build
      # 1. Install the SSH identifier from action secrets 
      # 2. Kill the app (unlocks the binary for writing)
      # 3. Copy app binary to server
      # 4. Also copy static files also needed by the binaries
    - name: Copy to Remote Server
      run: >-
        mkdir -p $HOME/.ssh; (echo "${{ secrets.SSH_KEY }}" > $HOME/.ssh/id_rsa); chmod 0600 $HOME/.ssh/id_rsa;
        ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa -r dist/* ${{ env.SERVER_HOST }}:./public_html;